import type {
  DemoCompanyDef,
  DemoDataset,
  DemoEmailDef,
  DemoIssueAssignmentDef,
  DemoListDef,
  DemoNewsletterDef,
  DemoPersonDef,
  DemoSubmissionDef,
  DemoTaskDef,
  DemoTeamDef,
  DemoUserDef,
  DemoVolunteerEventDef,
  DemoDonationDef,
  DemoPledgeDef,
  DemoReceiptDef,
  DemoStatementRunDef,
} from './demo-data-types';
import { DEMO_CITY, DEMO_COUNTRY, DEMO_STATE, allSites } from './demo-data-places';

/**
 * The demo workspace for CHURCH mode: Riverside Community Church, a fictional Ottawa
 * congregation of about 140 on a Sunday.
 *
 * What makes it a church dataset rather than the campaign one with the words swapped:
 * - The household leads, not the individual. Families are entered together and the notes read
 *   like a congregation's memory ("new since Easter", "hosts the Tuesday study") rather than a
 *   voter file. This is the whole promise of the church landing page — "Know every family by
 *   name" — and the demo data is where that claim is either true or embarrassing.
 * - Nobody has a support level or a voting status. A congregation does not canvass for votes.
 * - No turfs and no delivery routes: church mode hides canvassing and deliveries by default. The
 *   equivalent work — pastoral visits — lives in tasks and the care-team list instead, which is
 *   the same shape of work without pretending a hidden module exists.
 * - Giving, not fundraising. Tithes and pledges, receipted, with the December spike that every
 *   church's ledger actually has.
 *
 * Vocabulary is constrained to what church signup seeds: SHARED_STARTER_TAGS plus
 * MODE_EXTRA_TAGS.church ('member', 'regular attender', 'newcomer'), MODE_ISSUES.church
 * (benevolence, missions, youth & families, community outreach), and the starter forms including
 * 'prayer-request'. `demo-datasets.spec.ts` enforces every one of those.
 */

const COMPANIES: DemoCompanyDef[] = [
  {
    key: 'co-riverside-school',
    name: 'Riverside Public School',
    description: 'Shares the gym for the youth program on Friday evenings.',
    website: 'https://riverside-ps.example.org',
    email: 'office@riverside-ps.example.org',
    phone: '613-555-0410',
    industry: 'Education',
  },
  {
    key: 'co-wellington-bakery',
    name: 'Wellington Bakery',
    description: 'Donates what is left on Saturday night for the Sunday welcome table.',
    website: 'https://wellington-bakery.example.com',
    email: 'hello@wellington-bakery.example.com',
    phone: '613-555-0411',
    industry: 'Food',
  },
  {
    key: 'co-hope-shelter',
    name: 'Hope Street Shelter',
    description: 'Mission partner — the congregation cooks and serves the third Saturday of each month.',
    website: 'https://hope-street.example.org',
    email: 'volunteers@hope-street.example.org',
    phone: '613-555-0412',
    industry: 'Social services',
  },
  {
    key: 'co-carleton-hospital',
    name: 'Carleton General Hospital',
    description: 'Where most of the hospital visits happen. Chaplaincy office coordinates access.',
    website: 'https://carleton-general.example.org',
    email: 'chaplaincy@carleton-general.example.org',
    phone: '613-555-0413',
    industry: 'Healthcare',
  },
  {
    key: 'co-bridgeview-seniors',
    name: 'Bridgeview Seniors Residence',
    description: 'Four members live here. Communion is brought on the first Sunday of the month.',
    website: 'https://bridgeview-seniors.example.com',
    email: 'reception@bridgeview-seniors.example.com',
    phone: '613-555-0414',
    industry: 'Senior care',
  },
];

const HOUSEHOLDS = allSites({
  'hh-cooper': { notes: 'Hosts the Tuesday evening study — park on the street, not the drive.' },
  'hh-gladstone': { notes: 'Buzzer broken — call up from the lobby.' },
  'hh-huron': { notes: 'New to the city in January. Two children in Sunday school.' },
  'hh-fifth': { notes: 'Communion brought monthly; Sunday mornings are hard now.' },
  'hh-kilborn-import': { notes: 'Came across on the old directory spreadsheet.' },
});

const PERSONS: DemoPersonDef[] = [
  // ── The Ramos family ──────────────────────────────────────────────────────
  {
    key: 'elena-ramos',
    first_name: 'Elena',
    last_name: 'Ramos',
    household: 'hh-cooper',
    email: 'elena.ramos@example.com',
    mobile: '613-555-0201',
    notes: 'Hosts the Tuesday study. Knows when someone has stopped coming before anyone else does.',
    createdDaysAgo: 330,
    tags: ['member', 'community leader'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'miguel-ramos',
    first_name: 'Miguel',
    last_name: 'Ramos',
    household: 'hh-cooper',
    email: 'miguel.ramos@example.com',
    mobile: '613-555-0202',
    notes: 'Sound desk most Sundays. Travels for work every other week.',
    createdDaysAgo: 330,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'sofia-ramos',
    first_name: 'Sofia',
    last_name: 'Ramos',
    household: 'hh-cooper',
    createdDaysAgo: 330,
    notes: 'Age 8 — Sunday school, and increasingly the one who sets up the chairs.',
  },

  // ── Long-standing members ─────────────────────────────────────────────────
  {
    key: 'harold-benning',
    first_name: 'Harold',
    last_name: 'Benning',
    household: 'hh-maclaren',
    email: 'h.benning@example.com',
    mobile: '613-555-0203',
    notes: 'Elder. Forty-one years here. Handles the benevolence fund with June.',
    createdDaysAgo: 350,
    tags: ['member', 'senior'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'june-benning',
    first_name: 'June',
    last_name: 'Benning',
    household: 'hh-maclaren',
    email: 'june.benning@example.com',
    notes: 'Runs the meal train. Ask her before promising anyone a casserole.',
    createdDaysAgo: 350,
    tags: ['member', 'senior'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'david-okafor',
    first_name: 'David',
    last_name: 'Okafor',
    household: 'hh-frank',
    email: 'david.okafor@example.com',
    mobile: '613-555-0204',
    notes: 'Leads the Friday youth program. Teacher by day at Riverside PS.',
    company: 'co-riverside-school',
    createdDaysAgo: 300,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'blessing-okafor',
    first_name: 'Blessing',
    last_name: 'Okafor',
    household: 'hh-frank',
    email: 'blessing.okafor@example.com',
    createdDaysAgo: 300,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'daniel-okafor',
    first_name: 'Daniel',
    last_name: 'Okafor',
    household: 'hh-frank',
    email: 'daniel.okafor@example.com',
    createdDaysAgo: 300,
    tags: ['student'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'margaret-liu',
    first_name: 'Margaret',
    last_name: 'Liu',
    household: 'hh-arlington',
    email: 'margaret.liu@example.com',
    mobile: '613-555-0205',
    notes: 'Treasurer. Counts the offering with Harold after the second service.',
    createdDaysAgo: 315,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'kenneth-liu',
    first_name: 'Kenneth',
    last_name: 'Liu',
    household: 'hh-arlington',
    email: 'kenneth.liu@example.com',
    createdDaysAgo: 315,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'patricia-nowak',
    first_name: 'Patricia',
    last_name: 'Nowak',
    household: 'hh-gladstone',
    email: 'p.nowak@example.com',
    notes: 'Plays piano on the weeks Grace is away.',
    createdDaysAgo: 288,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'stefan-nowak',
    first_name: 'Stefan',
    last_name: 'Nowak',
    household: 'hh-gladstone',
    createdDaysAgo: 288,
    tags: ['regular attender'],
  },

  // ── Regular attenders ─────────────────────────────────────────────────────
  {
    key: 'ade-balogun',
    first_name: 'Ade',
    last_name: 'Balogun',
    household: 'hh-bay',
    email: 'ade.balogun@example.com',
    mobile: '613-555-0206',
    notes: 'Comes most weeks, has not joined. Says he is "still deciding" and enjoys being asked.',
    createdDaysAgo: 205,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'funke-balogun',
    first_name: 'Funke',
    last_name: 'Balogun',
    household: 'hh-bay',
    email: 'funke.balogun@example.com',
    createdDaysAgo: 205,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'colin-mercer',
    first_name: 'Colin',
    last_name: 'Mercer',
    household: 'hh-byron',
    company: 'co-wellington-bakery',
    email: 'colin@wellington-bakery.example.com',
    mobile: '613-555-0207',
    notes: 'Brings Saturday’s leftovers for the welcome table. Rarely stays for the service.',
    createdDaysAgo: 190,
    tags: ['regular attender', 'small business owner'],
    subscribed: true,
  },
  {
    key: 'ruth-mercer',
    first_name: 'Ruth',
    last_name: 'Mercer',
    household: 'hh-byron',
    email: 'ruth.mercer@example.com',
    createdDaysAgo: 190,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'grace-adeyemi',
    first_name: 'Grace',
    last_name: 'Adeyemi',
    household: 'hh-kirkwood',
    email: 'grace.adeyemi@example.com',
    mobile: '613-555-0208',
    notes: 'Music. Has run the Sunday team for three years and is quietly ready for a break.',
    createdDaysAgo: 270,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'tobi-adeyemi',
    first_name: 'Tobi',
    last_name: 'Adeyemi',
    household: 'hh-kirkwood',
    email: 'tobi.adeyemi@example.com',
    createdDaysAgo: 270,
    tags: ['student'],
    volunteerStatus: 'active',
  },

  // ── Newcomers ─────────────────────────────────────────────────────────────
  {
    key: 'nadia-haddad',
    first_name: 'Nadia',
    last_name: 'Haddad',
    household: 'hh-huron',
    email: 'nadia.haddad@example.com',
    mobile: '613-555-0209',
    notes: 'New to the city in January. Came the first Sunday after and has not missed one since.',
    createdDaysAgo: 84,
    tags: ['newcomer'],
    subscribed: true,
  },
  {
    key: 'karim-haddad',
    first_name: 'Karim',
    last_name: 'Haddad',
    household: 'hh-huron',
    email: 'karim.haddad@example.com',
    createdDaysAgo: 84,
    tags: ['newcomer'],
    subscribed: true,
  },
  {
    key: 'layla-haddad',
    first_name: 'Layla',
    last_name: 'Haddad',
    household: 'hh-huron',
    createdDaysAgo: 84,
    notes: 'Age 6 — Sunday school.',
  },
  {
    key: 'omar-haddad',
    first_name: 'Omar',
    last_name: 'Haddad',
    household: 'hh-huron',
    createdDaysAgo: 84,
    notes: 'Age 4 — nursery.',
  },
  {
    key: 'siobhan-doyle',
    first_name: 'Siobhan',
    last_name: 'Doyle',
    household: 'hh-java',
    email: 'siobhan.doyle@example.com',
    mobile: '613-555-0210',
    notes: 'Visited twice since Easter. Welcome card sent; no follow-up yet.',
    createdDaysAgo: 38,
    tags: ['newcomer'],
    subscribed: true,
  },
  {
    key: 'peter-doyle',
    first_name: 'Peter',
    last_name: 'Doyle',
    household: 'hh-java',
    createdDaysAgo: 38,
    tags: ['newcomer'],
  },
  {
    key: 'amara-nwosu',
    first_name: 'Amara',
    last_name: 'Nwosu',
    household: 'hh-armstrong',
    email: 'amara.nwosu@example.com',
    notes: 'First visit three weeks ago, brought by the Balogans. Asked about the youth program.',
    createdDaysAgo: 22,
    tags: ['newcomer'],
    subscribed: true,
  },
  {
    key: 'chidi-nwosu',
    first_name: 'Chidi',
    last_name: 'Nwosu',
    household: 'hh-armstrong',
    createdDaysAgo: 22,
    tags: ['newcomer', 'student'],
  },

  // ── Members needing care ──────────────────────────────────────────────────
  {
    key: 'eunice-tremblay',
    first_name: 'Eunice',
    last_name: 'Tremblay',
    household: 'hh-fifth',
    company: 'co-bridgeview-seniors',
    email: 'eunice.t@example.com',
    notes: 'At Bridgeview since March. Communion brought monthly; Sundays are hard now.',
    createdDaysAgo: 345,
    tags: ['member', 'senior'],
  },
  {
    key: 'gilles-tremblay',
    first_name: 'Gilles',
    last_name: 'Tremblay',
    household: 'hh-fifth',
    notes: 'Visits Eunice daily. Has not been to a service since she moved.',
    createdDaysAgo: 345,
    tags: ['member', 'senior'],
  },
  {
    key: 'walter-hume',
    first_name: 'Walter',
    last_name: 'Hume',
    household: 'hh-holmwood',
    email: 'walter.hume@example.com',
    mobile: '613-555-0211',
    notes: 'Knee replacement on the 9th — in Carleton General for a few days.',
    createdDaysAgo: 260,
    tags: ['member', 'senior'],
    subscribed: true,
  },
  {
    key: 'irene-hume',
    first_name: 'Irene',
    last_name: 'Hume',
    household: 'hh-holmwood',
    email: 'irene.hume@example.com',
    createdDaysAgo: 260,
    tags: ['member', 'senior'],
    subscribed: true,
  },
  {
    key: 'martha-sinclair',
    first_name: 'Martha',
    last_name: 'Sinclair',
    household: 'hh-sunnyside',
    email: 'martha.sinclair@example.com',
    notes: 'Widowed in February. June has the meal train going; visits still matter more.',
    createdDaysAgo: 320,
    tags: ['member', 'senior'],
    subscribed: true,
  },

  // ── Wider congregation ────────────────────────────────────────────────────
  {
    key: 'joseph-kimani',
    first_name: 'Joseph',
    last_name: 'Kimani',
    household: 'hh-powell',
    email: 'joseph.kimani@example.com',
    mobile: '613-555-0212',
    notes: 'Organizes the Hope Street cooking rota.',
    company: 'co-hope-shelter',
    createdDaysAgo: 240,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'esther-kimani',
    first_name: 'Esther',
    last_name: 'Kimani',
    household: 'hh-powell',
    email: 'esther.kimani@example.com',
    createdDaysAgo: 240,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'brian-whelan',
    first_name: 'Brian',
    last_name: 'Whelan',
    household: 'hh-aylmer',
    email: 'brian.whelan@example.com',
    createdDaysAgo: 225,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'karen-whelan',
    first_name: 'Karen',
    last_name: 'Whelan',
    household: 'hh-aylmer',
    email: 'karen.whelan@example.com',
    notes: 'Sunday school coordinator. Needs two more teachers before September.',
    createdDaysAgo: 225,
    tags: ['member'],
    subscribed: true,
    volunteerStatus: 'active',
  },
  {
    key: 'mei-lin-chow',
    first_name: 'Mei-Lin',
    last_name: 'Chow',
    household: 'hh-sweetland',
    email: 'meilin.chow@example.com',
    createdDaysAgo: 180,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'anthony-chow',
    first_name: 'Anthony',
    last_name: 'Chow',
    household: 'hh-sweetland',
    email: 'anthony.chow@example.com',
    createdDaysAgo: 180,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'rebecca-stein',
    first_name: 'Rebecca',
    last_name: 'Stein',
    household: 'hh-marlborough',
    email: 'rebecca.stein@example.com',
    createdDaysAgo: 165,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'thomas-nkemelu',
    first_name: 'Thomas',
    last_name: 'Nkemelu',
    household: 'hh-blackburn',
    email: 'thomas.nkemelu@example.com',
    mobile: '613-555-0213',
    createdDaysAgo: 150,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'chioma-nkemelu',
    first_name: 'Chioma',
    last_name: 'Nkemelu',
    household: 'hh-blackburn',
    email: 'chioma.nkemelu@example.com',
    createdDaysAgo: 150,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'alan-forsyth',
    first_name: 'Alan',
    last_name: 'Forsyth',
    household: 'hh-charlotte',
    email: 'alan.forsyth@example.com',
    createdDaysAgo: 132,
    tags: ['member', 'letter writer'],
    subscribed: true,
  },
  {
    key: 'dorothy-forsyth',
    first_name: 'Dorothy',
    last_name: 'Forsyth',
    household: 'hh-charlotte',
    createdDaysAgo: 132,
    tags: ['member', 'senior'],
  },
  {
    key: 'sunil-mehta',
    first_name: 'Sunil',
    last_name: 'Mehta',
    household: 'hh-kilborn',
    email: 'sunil.mehta@example.com',
    createdDaysAgo: 118,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'anita-mehta',
    first_name: 'Anita',
    last_name: 'Mehta',
    household: 'hh-kilborn',
    email: 'anita.mehta@example.com',
    createdDaysAgo: 118,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'paul-doucette',
    first_name: 'Paul',
    last_name: 'Doucette',
    household: 'hh-pleasantpark',
    email: 'paul.doucette@example.com',
    createdDaysAgo: 100,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'lise-doucette',
    first_name: 'Lise',
    last_name: 'Doucette',
    household: 'hh-pleasantpark',
    email: 'lise.doucette@example.com',
    createdDaysAgo: 100,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'samuel-boateng',
    first_name: 'Samuel',
    last_name: 'Boateng',
    household: 'hh-halifax',
    email: 'samuel.boateng@example.com',
    createdDaysAgo: 88,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'akosua-boateng',
    first_name: 'Akosua',
    last_name: 'Boateng',
    household: 'hh-halifax',
    email: 'akosua.boateng@example.com',
    createdDaysAgo: 88,
    tags: ['member'],
    subscribed: true,
  },
  {
    key: 'yolanda-cruz',
    first_name: 'Yolanda',
    last_name: 'Cruz',
    household: 'hh-featherston',
    email: 'yolanda.cruz@example.com',
    createdDaysAgo: 66,
    tags: ['regular attender'],
    subscribed: true,
  },
  {
    key: 'edwin-park',
    first_name: 'Edwin',
    last_name: 'Park',
    household: 'hh-kilborn-import',
    email: 'edwin.park@example.com',
    notes: 'On the old directory but nobody has seen him in two years. Worth a call before the next print.',
    createdDaysAgo: 358,
    tags: ['member'],
  },
  {
    key: 'monique-arsenault',
    first_name: 'Monique',
    last_name: 'Arsenault',
    email: 'monique.arsenault@example.com',
    mobile: '613-555-0214',
    notes: 'Found us through the website. Has not visited yet.',
    createdDaysAgo: 16,
    tags: ['newcomer'],
    subscribed: true,
  },
  {
    key: 'trevor-oyelaran',
    first_name: 'Trevor',
    last_name: 'Oyelaran',
    email: 'trevor.oyelaran@example.com',
    createdDaysAgo: 7,
    tags: ['newcomer'],
    subscribed: true,
  },
];

const USERS: DemoUserDef[] = [
  { key: 'u-pastor', first_name: 'Rachel', last_name: 'Adeyinka', emailLocal: 'rachel', role: 'admin' },
  { key: 'u-admin', first_name: 'Gordon', last_name: 'Pike', emailLocal: 'gordon', role: 'user' },
  { key: 'u-care', first_name: 'Naomi', last_name: 'Feldman', emailLocal: 'naomi', role: 'user' },
];

const TASKS: DemoTaskDef[] = [
  {
    name: 'Visit Walter Hume at Carleton General',
    details: 'Knee replacement on the 9th. Chaplaincy office needs a name at the desk — Rachel or Naomi.',
    status: 'todo',
    priority: 'urgent',
    position: 1,
    dueInDays: 1,
    assignToUser: 'u-care',
  },
  {
    name: 'Follow up with the Doyles',
    details: 'Two visits since Easter, welcome card sent, nothing since. A phone call is overdue.',
    status: 'todo',
    priority: 'high',
    position: 2,
    dueInDays: 3,
    assignToUser: 'u-pastor',
  },
  {
    name: 'Take communion to Bridgeview',
    details: 'First Sunday of the month. Eunice, and three others on the floor above.',
    status: 'todo',
    priority: 'high',
    position: 3,
    dueInDays: 5,
    assignToUser: 'u-care',
  },
  {
    name: 'Two more Sunday school teachers before September',
    details: 'Karen is short-handed. Ask the Boatengs and Chioma before putting it in the bulletin.',
    status: 'in_progress',
    priority: 'high',
    position: 4,
    dueInDays: 24,
    assignToOwner: true,
  },
  {
    name: 'Benevolence request — the Nwosu family',
    details: 'Harold and June reviewing. Rent shortfall, one month. Decision needed before the 20th.',
    status: 'waiting',
    priority: 'urgent',
    position: 5,
    dueInDays: 6,
    assignToOwner: true,
  },
  {
    name: 'Call Edwin Park before the directory goes to print',
    details: 'On the roll for years, unseen for two. Find out whether he wants to stay on the list.',
    status: 'todo',
    priority: 'low',
    position: 6,
    dueInDays: 18,
    assignToUser: 'u-admin',
  },
  {
    name: 'Ask Grace about a break from the music rota',
    details: 'Three years running the team. She has not asked, which is exactly why to ask her.',
    status: 'todo',
    priority: 'medium',
    position: 7,
    dueInDays: 12,
    assignToUser: 'u-pastor',
  },
  {
    name: 'Confirm the Hope Street cooking rota for next quarter',
    details: 'Joseph has the sign-ups. Third Saturday each month; we are one short in August.',
    status: 'todo',
    priority: 'medium',
    position: 8,
    dueInDays: 15,
    assignToUser: 'u-admin',
  },
  {
    name: 'Send the giving statements',
    details:
      'Ran last year from Giving → Receipts & statements. Two households have no email — download theirs from the same page and mail them.',
    status: 'done',
    priority: 'high',
    position: 9,
    completedDaysAgo: 11,
    assignToUser: 'u-admin',
  },
  {
    name: 'Meal train for Martha Sinclair',
    details: 'Three weeks arranged. June has the sign-up sheet.',
    status: 'done',
    priority: 'high',
    position: 10,
    completedDaysAgo: 26,
    assignToUser: 'u-care',
  },
];

const LISTS: DemoListDef[] = [
  {
    key: 'list-newcomers',
    name: 'Newcomers — last 90 days',
    description: 'Anyone who has visited since Easter. The follow-up list, worked through every Monday.',
    members: [
      'nadia-haddad',
      'karim-haddad',
      'siobhan-doyle',
      'peter-doyle',
      'amara-nwosu',
      'chidi-nwosu',
      'monique-arsenault',
      'trevor-oyelaran',
    ],
  },
  {
    key: 'list-care',
    name: 'Care visits',
    description: 'Members in hospital, in residence, or recently bereaved. Reviewed at the Tuesday staff meeting.',
    members: ['eunice-tremblay', 'gilles-tremblay', 'walter-hume', 'irene-hume', 'martha-sinclair'],
  },
  {
    key: 'list-serving',
    name: 'Serving on a Sunday',
    description: 'Music, sound, welcome table, Sunday school and nursery — everyone on a rota.',
    members: [
      'elena-ramos',
      'miguel-ramos',
      'grace-adeyemi',
      'tobi-adeyemi',
      'patricia-nowak',
      'karen-whelan',
      'david-okafor',
      'daniel-okafor',
      'joseph-kimani',
    ],
  },
  {
    key: 'list-subscribers',
    name: 'Newsletter subscribers',
    description: 'Everyone who has opted in to the weekly email.',
    members: [
      'elena-ramos',
      'miguel-ramos',
      'harold-benning',
      'june-benning',
      'david-okafor',
      'blessing-okafor',
      'daniel-okafor',
      'margaret-liu',
      'kenneth-liu',
      'patricia-nowak',
      'ade-balogun',
      'funke-balogun',
      'colin-mercer',
      'ruth-mercer',
      'grace-adeyemi',
      'nadia-haddad',
      'karim-haddad',
      'siobhan-doyle',
      'amara-nwosu',
      'walter-hume',
      'irene-hume',
      'martha-sinclair',
      'joseph-kimani',
      'esther-kimani',
      'brian-whelan',
      'karen-whelan',
      'mei-lin-chow',
      'anthony-chow',
      'rebecca-stein',
      'thomas-nkemelu',
      'chioma-nkemelu',
      'alan-forsyth',
      'sunil-mehta',
      'anita-mehta',
      'paul-doucette',
      'lise-doucette',
      'samuel-boateng',
      'akosua-boateng',
      'yolanda-cruz',
      'monique-arsenault',
      'trevor-oyelaran',
    ],
  },
];

const TEAM: DemoTeamDef = {
  name: 'Care team',
  description: 'Hospital visits, communion at Bridgeview, and the meal train.',
  members: ['june-benning', 'harold-benning', 'martha-sinclair'],
};

const VOLUNTEER_EVENTS: DemoVolunteerEventDef[] = [
  {
    key: 'ev-hope-street',
    name: 'Hope Street — cook and serve',
    description:
      'Third Saturday of the month. Six people cook from 3pm, serve at 5:30, and are home by 8. No experience needed; Joseph will show you the kitchen.',
    location_address: '211 Hope St, Ottawa, ON K1N 7B4',
    slug: 'hope-street-cook-and-serve',
    startInDays: 11,
    durationHours: 5,
    capacity: 8,
    shifts: [
      { person: 'joseph-kimani', status: 'signed_up' },
      { person: 'esther-kimani', status: 'signed_up' },
      { person: 'daniel-okafor', status: 'signed_up' },
      { person: 'ade-balogun', status: 'signed_up' },
    ],
  },
  {
    key: 'ev-newcomers-lunch',
    name: 'Newcomers lunch',
    description:
      'Lunch after the second service for anyone who has started coming recently — and whoever invited them. Held in the hall, about ninety minutes.',
    location_address: '1064 Wellington St W, Ottawa, ON K1Y 2Y3',
    slug: 'newcomers-lunch',
    startInDays: -9,
    durationHours: 2,
    capacity: 25,
    shifts: [
      { person: 'nadia-haddad', status: 'attended' },
      { person: 'karim-haddad', status: 'attended' },
      { person: 'amara-nwosu', status: 'attended' },
      { person: 'elena-ramos', status: 'attended' },
      { person: 'siobhan-doyle', status: 'signed_up' },
    ],
  },
];

const WEEKLY_LINKS = {
  serve: 'https://example.org/serve',
  give: 'https://example.org/give',
  hopestreet: 'https://example.org/hope-street',
};

const NEWSLETTERS: DemoNewsletterDef[] = [
  {
    key: 'nl-this-week',
    name: 'This week at Riverside',
    status: 'sent',
    subject: 'Sunday school needs two teachers — and Walter comes home Thursday',
    preview_text: 'What is on this week, who to pray for, and one ask.',
    audience_description: 'Newsletter subscribers',
    sentDaysAgo: 5,
    links: [WEEKLY_LINKS.serve, WEEKLY_LINKS.hopestreet, WEEKLY_LINKS.give],
    html_content:
      '<h1>This week at Riverside</h1>' +
      '<p><strong>Walter Hume</strong> comes home Thursday after his surgery. Irene says visits are welcome from the ' +
      'weekend onward — call first.</p>' +
      '<p><strong>Sunday school is two teachers short</strong> before September. It is one Sunday a month, the ' +
      'material is written for you, and Karen will sit with you the first time. ' +
      '<a href="https://example.org/serve">Say yes here</a>.</p>' +
      '<p><strong>Hope Street</strong> is the third Saturday — six of us cook and serve, home by eight. ' +
      '<a href="https://example.org/hope-street">Sign up</a>.</p>' +
      '<p>The Tuesday study is at the Ramos house as usual, 7:30. Park on the street.</p>' +
      '<p>Giving statements went out by email last week; if yours did not arrive, tell Gordon ' +
      'and he will print you one. You can also <a href="https://example.org/give">give online</a>.</p>',
    plain_text_content:
      'Walter Hume comes home Thursday. Sunday school needs two teachers before September — https://example.org/serve. ' +
      'Hope Street cook-and-serve is the third Saturday — https://example.org/hope-street. ' +
      'Tuesday study at the Ramos house, 7:30. Give online: https://example.org/give',
    recipients: [
      'elena-ramos',
      'miguel-ramos',
      'harold-benning',
      'june-benning',
      'david-okafor',
      'blessing-okafor',
      'daniel-okafor',
      'margaret-liu',
      'kenneth-liu',
      'patricia-nowak',
      'ade-balogun',
      'funke-balogun',
      'colin-mercer',
      'ruth-mercer',
      'grace-adeyemi',
      'nadia-haddad',
      'karim-haddad',
      'siobhan-doyle',
      'amara-nwosu',
      'walter-hume',
      'irene-hume',
      'martha-sinclair',
      'joseph-kimani',
      'esther-kimani',
      'brian-whelan',
      'karen-whelan',
      'mei-lin-chow',
      'anthony-chow',
      'rebecca-stein',
      'thomas-nkemelu',
      'chioma-nkemelu',
      'alan-forsyth',
      'sunil-mehta',
      'anita-mehta',
      'paul-doucette',
      'lise-doucette',
      'samuel-boateng',
      'akosua-boateng',
      'yolanda-cruz',
    ],
    engagement: [
      { person: 'elena-ramos', opens: 3, clicks: [WEEKLY_LINKS.serve] },
      { person: 'miguel-ramos', opens: 1 },
      { person: 'harold-benning', opens: 2, clicks: [WEEKLY_LINKS.give] },
      { person: 'june-benning', opens: 3, clicks: [WEEKLY_LINKS.serve, WEEKLY_LINKS.hopestreet] },
      { person: 'david-okafor', opens: 2, clicks: [WEEKLY_LINKS.serve] },
      { person: 'blessing-okafor', opens: 1 },
      { person: 'daniel-okafor', opens: 2, clicks: [WEEKLY_LINKS.hopestreet] },
      { person: 'margaret-liu', opens: 4, clicks: [WEEKLY_LINKS.give] },
      { person: 'kenneth-liu', opens: 1 },
      { person: 'patricia-nowak', opens: 2 },
      { person: 'ade-balogun', opens: 2, clicks: [WEEKLY_LINKS.hopestreet] },
      { person: 'funke-balogun', opens: 1 },
      { person: 'grace-adeyemi', opens: 3, clicks: [WEEKLY_LINKS.serve] },
      { person: 'nadia-haddad', opens: 2 },
      { person: 'karim-haddad', opens: 1 },
      { person: 'siobhan-doyle', opens: 1 },
      { person: 'amara-nwosu', opens: 2, clicks: [WEEKLY_LINKS.serve] },
      { person: 'irene-hume', opens: 3 },
      { person: 'martha-sinclair', opens: 2 },
      { person: 'joseph-kimani', opens: 2, clicks: [WEEKLY_LINKS.hopestreet] },
      { person: 'esther-kimani', opens: 1 },
      { person: 'karen-whelan', opens: 4, clicks: [WEEKLY_LINKS.serve] },
      { person: 'brian-whelan', opens: 1 },
      { person: 'mei-lin-chow', opens: 1 },
      { person: 'rebecca-stein', opens: 1 },
      { person: 'thomas-nkemelu', opens: 2 },
      { person: 'alan-forsyth', opens: 2, clicks: [WEEKLY_LINKS.give] },
      { person: 'sunil-mehta', opens: 1 },
      { person: 'paul-doucette', opens: 1 },
      { person: 'samuel-boateng', opens: 2 },
      { person: 'akosua-boateng', opens: 1 },
      { person: 'yolanda-cruz', opens: 0, bounce: 'soft' },
      { person: 'colin-mercer', opens: 0, unsubscribed: true },
    ],
  },
  {
    key: 'nl-advent',
    name: 'Advent services',
    status: 'draft',
    subject: 'Four Sundays, one late night, and Christmas Eve',
    preview_text: 'The full Advent schedule, and where the extra hands are needed.',
    audience_description: 'Newsletter subscribers',
    links: [WEEKLY_LINKS.serve],
    html_content:
      '<h1>Advent at Riverside</h1>' +
      '<p>Four Sunday evenings, the late carol service on the 22nd, and two services on Christmas Eve — 4pm for ' +
      'families, 10pm for everyone else.</p>' +
      '<p>The 4pm service needs help with the children’s nativity, and the 10pm needs three more on the welcome ' +
      'table. <a href="https://example.org/serve">Both are here</a>.</p>' +
      '<p>If you would like communion brought to you over Advent, tell Naomi and it is arranged.</p>',
    plain_text_content:
      'Advent: four Sunday evenings, carols on the 22nd, and Christmas Eve at 4pm and 10pm. ' +
      'Help needed with the nativity and the welcome table: https://example.org/serve. ' +
      'Communion can be brought to you over Advent — tell Naomi.',
  },
];

const SUBMISSIONS: DemoSubmissionDef[] = [
  {
    formSlug: 'newsletter-sign-up',
    person: 'monique-arsenault',
    daysAgo: 16,
    answers: { first_name: 'Monique', last_name: 'Arsenault', email: 'monique.arsenault@example.com' },
  },
  {
    formSlug: 'newsletter-sign-up',
    person: 'trevor-oyelaran',
    daysAgo: 7,
    answers: { first_name: 'Trevor', last_name: 'Oyelaran', email: 'trevor.oyelaran@example.com' },
  },
  {
    formSlug: 'newsletter-sign-up',
    person: 'amara-nwosu',
    daysAgo: 22,
    answers: { first_name: 'Amara', last_name: 'Nwosu', email: 'amara.nwosu@example.com' },
  },
  {
    formSlug: 'prayer-request',
    person: 'irene-hume',
    daysAgo: 4,
    answers: {
      first_name: 'Irene',
      last_name: 'Hume',
      email: 'irene.hume@example.com',
      message: 'Walter’s surgery is on the 9th. Please pray it goes simply and he is home by the weekend.',
    },
  },
  {
    formSlug: 'prayer-request',
    person: 'siobhan-doyle',
    daysAgo: 13,
    answers: {
      first_name: 'Siobhan',
      last_name: 'Doyle',
      email: 'siobhan.doyle@example.com',
      message: 'Starting a new job next month after a long stretch out of work. Grateful and nervous.',
    },
  },
  {
    formSlug: 'prayer-request',
    person: 'amara-nwosu',
    daysAgo: 19,
    answers: {
      first_name: 'Amara',
      last_name: 'Nwosu',
      email: 'amara.nwosu@example.com',
      message: 'For our family as we settle — and thank you for the welcome on Sunday.',
    },
  },
];

const ISSUE_ASSIGNMENTS: DemoIssueAssignmentDef[] = [
  { issue: 'benevolence', people: ['amara-nwosu', 'chidi-nwosu', 'harold-benning', 'june-benning'] },
  { issue: 'missions', people: ['joseph-kimani', 'esther-kimani', 'david-okafor'] },
  { issue: 'youth & families', people: ['karen-whelan', 'david-okafor', 'daniel-okafor', 'tobi-adeyemi'] },
  { issue: 'community outreach', people: ['colin-mercer', 'ade-balogun', 'elena-ramos'] },
];

const EMAILS: DemoEmailDef[] = [
  {
    folder: 'inbox',
    person: 'irene-hume',
    subject: 'Walter — surgery Tuesday',
    preview_text: 'They have him down for Tuesday morning at Carleton General —',
    status: 'open',
    assignTo: 'u-care',
    daysAgo: 1,
    is_favourite: true,
    body_html:
      '<p>They have him down for Tuesday morning at Carleton General. He is pretending not to be nervous.</p>' +
      '<p>Visits after the weekend would be lovely — before that he will be asleep or complaining. I will let you ' +
      'know when he is on a ward.</p><p>Irene</p>',
  },
  {
    folder: 'inbox',
    person: 'siobhan-doyle',
    subject: 'Is there a mid-week group?',
    preview_text: 'We came the last two Sundays and wondered —',
    status: 'open',
    assignTo: 'u-pastor',
    daysAgo: 2,
    body_html:
      '<p>Hello,</p><p>We came the last two Sundays and wondered whether there is anything mid-week. Peter works ' +
      'shifts so Sundays are hit and miss for him, but I could come to something in the evening.</p>' +
      '<p>Also — is there anything for a nine-year-old? Ours is at the age where she wants her own thing.</p>' +
      '<p>Siobhan</p>',
  },
  {
    folder: 'inbox',
    person: 'karen-whelan',
    subject: 'Sunday school — still two short',
    preview_text: 'I have asked everyone I can ask without it being awkward —',
    status: 'open',
    assignTo: 'owner',
    daysAgo: 4,
    body_html:
      '<p>I have asked everyone I can ask without it being awkward. Still two short for September.</p>' +
      '<p>Could it go in the newsletter with a proper ask rather than a line at the bottom? People say yes to a ' +
      'person, not a notice.</p><p>Karen</p>',
  },
  {
    folder: 'inbox',
    person: 'harold-benning',
    subject: 'Benevolence — the Nwosu request',
    preview_text: 'June and I have been through it —',
    status: 'closed',
    assignTo: 'owner',
    daysAgo: 7,
    body_html:
      '<p>June and I have been through it. One month of rent, and they have not asked before.</p>' +
      '<p>The fund can carry it without touching the reserve. We would like to say yes at Tuesday’s meeting unless ' +
      'you see a reason not to.</p><p>Harold</p>',
  },
  {
    folder: 'sent',
    person: 'nadia-haddad',
    subject: 'Re: Sunday school for Layla and Omar',
    preview_text: 'Both are very welcome — Layla is with the 5–8s —',
    status: 'closed',
    assignTo: 'u-pastor',
    daysAgo: 12,
    body_html:
      '<p>Hi Nadia,</p><p>Both are very welcome. Layla is with the 5–8s, and Omar can go to the nursery — same ' +
      'corridor, so drop-off is one stop.</p>' +
      '<p>Karen runs it and will find you on Sunday. And if it helps, the Ramos family live two streets from you ' +
      'and drive in each week.</p><p>Rachel</p>',
  },
  {
    folder: 'sent',
    person: 'grace-adeyemi',
    subject: 'A thought about the music rota',
    preview_text: 'Three years is a long time to carry something —',
    status: 'closed',
    assignTo: 'u-pastor',
    daysAgo: 20,
    body_html:
      '<p>Grace,</p><p>Three years is a long time to carry something without being asked how you are finding it. ' +
      'So — how are you finding it?</p>' +
      '<p>If a season off would help, we will make it work. Patricia can cover more than she lets on.</p>' +
      '<p>Rachel</p>',
  },
];

const PLEDGES: DemoPledgeDef[] = [
  { key: 'pl-benning', person: 'harold-benning', monthlyAmountCents: 30000, startedDaysAgo: 340, nextBillingInDays: 8 },
  { key: 'pl-liu', person: 'margaret-liu', monthlyAmountCents: 20000, startedDaysAgo: 300, nextBillingInDays: 3 },
  { key: 'pl-ramos', person: 'elena-ramos', monthlyAmountCents: 12500, startedDaysAgo: 210, nextBillingInDays: 15 },
  { key: 'pl-okafor', person: 'david-okafor', monthlyAmountCents: 10000, startedDaysAgo: 180, nextBillingInDays: 22 },
];

const DONATIONS: DemoDonationDef[] = [
  {
    person: 'harold-benning',
    amountCents: 30000,
    method: 'card',
    createdDaysAgo: 8,
    pledge: 'pl-benning',
  },
  {
    person: 'harold-benning',
    amountCents: 30000,
    method: 'card',
    createdDaysAgo: 38,
    pledge: 'pl-benning',
  },
  {
    person: 'margaret-liu',
    amountCents: 20000,
    method: 'card',
    createdDaysAgo: 3,
    pledge: 'pl-liu',
  },
  {
    person: 'margaret-liu',
    amountCents: 20000,
    method: 'card',
    createdDaysAgo: 33,
    pledge: 'pl-liu',
  },
  {
    person: 'elena-ramos',
    amountCents: 12500,
    method: 'card',
    createdDaysAgo: 15,
    pledge: 'pl-ramos',
  },
  {
    person: 'david-okafor',
    amountCents: 10000,
    method: 'card',
    createdDaysAgo: 22,
    pledge: 'pl-okafor',
  },
  { person: 'june-benning', amountCents: 5000, method: 'cash', createdDaysAgo: 6 },
  { person: 'joseph-kimani', amountCents: 15000, method: 'check', createdDaysAgo: 11 },
  { person: 'karen-whelan', amountCents: 7500, method: 'card', createdDaysAgo: 14 },
  { person: 'thomas-nkemelu', amountCents: 10000, method: 'bank_transfer', createdDaysAgo: 18 },
  { person: 'samuel-boateng', amountCents: 6000, method: 'cash', createdDaysAgo: 20 },
  { person: 'alan-forsyth', amountCents: 25000, method: 'check', createdDaysAgo: 27 },
  { person: 'mei-lin-chow', amountCents: 8000, method: 'card', createdDaysAgo: 31 },
  { person: 'paul-doucette', amountCents: 5000, method: 'card', createdDaysAgo: 36 },
  { person: 'ade-balogun', amountCents: 4000, method: 'cash', createdDaysAgo: 41 },
  { person: 'grace-adeyemi', amountCents: 9000, method: 'card', createdDaysAgo: 49 },
  { person: 'brian-whelan', amountCents: 12000, method: 'check', createdDaysAgo: 55 },
];

/**
 * Official receipts over DONATIONS (by index). Most one-time gifts are receipted (auto-issue is
 * on); a few cash gifts are deliberately not, so the "Receipts" stat is honest work-in-progress,
 * and Alan Forsyth's check carries the cancel-and-replace pair the receipts page demonstrates.
 *
 * `ref` is a label for the cancel-and-replace link below, not the printed number — the seeder
 * numbers these by issue date (see DemoReceiptDef).
 */
const RECEIPTS: DemoReceiptDef[] = [
  { donation: 7, ref: 1, issuedDaysAgo: 11, emailed: true }, // joseph-kimani, check
  { donation: 8, ref: 2, issuedDaysAgo: 14, emailed: true }, // karen-whelan, card
  { donation: 9, ref: 3, issuedDaysAgo: 18, emailed: false }, // thomas-nkemelu, bank transfer
  {
    donation: 11, // alan-forsyth, check — the misspelled-name receipt…
    ref: 4,
    issuedDaysAgo: 27,
    status: 'cancelled',
    cancelledReason: 'Donor name was misspelled',
  },
  { donation: 11, ref: 5, issuedDaysAgo: 26, replacesRef: 4, emailed: true }, // …and its replacement
  { donation: 12, ref: 6, issuedDaysAgo: 31, emailed: true }, // mei-lin-chow, card
];

/** CRA charitable receipting, configured the way a real church office would. */
const RECEIPT_SETTINGS: Record<string, string | boolean> = {
  'receipts.regime': 'cra_charity',
  'receipts.mode': 'per_gift',
  'receipts.auto_issue': true,
  'receipts.org_legal_name': 'Riverside Community Church',
  'receipts.org_address': `41 Chapel Street, ${DEMO_CITY}, ${DEMO_STATE}`,
  'receipts.registration_number': '123456789 RR 0001',
  'receipts.signatory_name': 'Margaret Liu',
  'receipts.signatory_title': 'Treasurer',
  'receipts.number_prefix': 'RCC',
  'receipts.place_of_issue': DEMO_CITY,
};

/** Last year's statement run — the "giving statements went out" the newsletter mentions. */
const STATEMENT_RUN: DemoStatementRunDef = {
  yearsAgo: 1,
  donorsTotal: 14,
  generated: 14,
  emailed: 12,
  toPrint: 2,
};

export const CHURCH_DEMO_DATASET: DemoDataset = {
  city: DEMO_CITY,
  state: DEMO_STATE,
  country: DEMO_COUNTRY,
  companies: COMPANIES,
  households: HOUSEHOLDS,
  persons: PERSONS,
  users: USERS,
  tasks: TASKS,
  lists: LISTS,
  team: TEAM,
  volunteerEvents: VOLUNTEER_EVENTS,
  newsletters: NEWSLETTERS,
  submissions: SUBMISSIONS,
  issueAssignments: ISSUE_ASSIGNMENTS,
  emails: EMAILS,
  // Church mode hides canvassing and deliveries by default; pastoral visits live in tasks.
  turfs: [],
  deliveryRequests: [],
  deliveryRoutes: [],
  pledges: PLEDGES,
  donations: DONATIONS,
  receipts: RECEIPTS,
  receiptSettings: RECEIPT_SETTINGS,
  statementRun: STATEMENT_RUN,
};
