import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { BaseRepository } from '../../../lib/base.repo';
import { DB_TEST_LOCKS, useExclusiveDbLock } from '../../../lib/test-utils/exclusive-db-lock';
import { DonationsController } from '../controller';
import { DonationReceiptsController } from './controller';

/**
 * Regression coverage for the cancel/reissue state machine in `DonationReceiptsController`
 * (apps/backend/src/app/modules/donations/receipts/controller.ts, `cancelReceipt` /
 * `reissueReceipt`), added following a production-risk review that flagged these refusal paths
 * as untested. The blast radius of a bug here is a statement — a donor's unnumbered whole-year
 * summary — getting "reissued" into a serialized (numbered) document, or a numbered document's
 * serial being reused/gapped.
 *
 * State machine as read from the source (kind: 'per_gift' | 'cumulative' | 'acknowledgement' |
 * 'statement'; status: 'issued' | 'cancelled'):
 *
 * cancelReceipt(receiptId, reason):
 *   - receipt not found (including wrong tenant, since getReceiptById is tenant-scoped) -> NotFoundError
 *   - kind === 'statement'                                    -> BadRequestError (never cancelled one-by-one)
 *   - status !== 'issued' (already cancelled)                 -> ConflictError
 *   - else: sets status='cancelled', cancelled_reason/at/by, reissue_required=false
 *
 * reissueReceipt(receiptId, reason?):
 *   - predecessor not found (including wrong tenant)           -> NotFoundError
 *   - kind === 'statement'                                     -> BadRequestError (regenerated by year-end rerun, not reissued)
 *   - kind === 'acknowledgement'                                -> BadRequestError (not reissued at all)
 *   - status === 'issued' && no reason given                    -> BadRequestError
 *   - workspace regime !== predecessor's frozen regime           -> PreconditionFailedError
 *   - every covered gift refunded (surviving.length === 0)       -> PreconditionFailedError
 *   - donor has no resolvable mailing address                    -> PreconditionFailedError
 *   - predecessor's frozen advantage_cents >= surviving amount    -> PreconditionFailedError
 *   - else: transaction takes a NEW serial from the counter, cancels the predecessor (if still
 *     'issued') or clears its reissue_required flag (if already cancelled), inserts a successor
 *     row with replaces_receipt_id = predecessor.id.
 *
 * Reissue's validation runs entirely before `nextSerial` is called inside the transaction, so a
 * refused reissue must never advance/reuse the receipt_counters sequence — pinned below.
 */

// Reissue commits real transactions against the shared receipt_counters row (the counter lock IS
// part of what several tests here pin), so this file takes the same lock the sibling
// controller.spec.ts does and the two take turns.
useExclusiveDbLock(DB_TEST_LOCKS.RECEIPT_COUNTERS);

const rand = () => String(Math.floor(Math.random() * 100000000) + 1000000);

async function cleanTenant(db: any, tenantId: string) {
  await db
    .updateTable('tenants')
    .set({ admin_id: null, createdby_id: null, placeholder_household_id: null })
    .where('id', '=', tenantId)
    .execute();
  for (const table of [
    'background_jobs',
    'donation_receipt_items',
    'donation_receipts',
    'files',
    'receipt_counters',
    'receipt_statement_runs',
    'donations',
    'settings',
    'persons',
    'households',
    'campaigns',
    'user_activity',
    'authusers',
  ]) {
    await db.deleteFrom(table).where('tenant_id', '=', tenantId).execute();
  }
  await db.deleteFrom('tenants').where('id', '=', tenantId).execute();
}

/** CRA-complete receipts.* settings; individual tests unset/override keys to exercise guards. */
async function seedReceiptSettings(db: any, tenantId: string, userId: string, overrides: Record<string, unknown> = {}) {
  const values: Record<string, unknown> = {
    'receipts.regime': 'cra_charity',
    'receipts.mode': 'per_gift',
    'receipts.org_legal_name': 'Test Charity',
    'receipts.org_address': '1 Test Way, Ottawa, ON',
    'receipts.registration_number': '123456789 RR 0001',
    'receipts.place_of_issue': 'Ottawa',
    'receipts.signatory_name': 'Pat Signer',
    'receipts.signature_file_id': '1',
    'receipts.number_prefix': 'T',
    ...overrides,
  };
  await db
    .insertInto('settings')
    .values(
      Object.entries(values)
        .filter(([, v]) => v !== undefined)
        .map(([key, value]) => ({
          tenant_id: tenantId,
          key,
          value: JSON.stringify(value),
          createdby_id: userId,
          updatedby_id: userId,
        })),
    )
    .execute();
}

/** Upsert a single receipts.* setting key without touching the others already seeded. */
async function setSetting(db: any, tenantId: string, userId: string, key: string, value: unknown) {
  await db.deleteFrom('settings').where('tenant_id', '=', tenantId).where('key', '=', key).execute();
  await db
    .insertInto('settings')
    .values({
      tenant_id: tenantId,
      key,
      value: JSON.stringify(value),
      createdby_id: userId,
      updatedby_id: userId,
    })
    .execute();
}

async function createSeed(db: any) {
  const tenantId = rand();
  const userId = rand();
  const campaignId = rand();
  const householdId = rand();
  const personId = rand();

  await db.insertInto('tenants').values({ id: tenantId, name: 'Cancel/Reissue Test Tenant' }).execute();
  await db
    .insertInto('authusers')
    .values({
      id: userId,
      tenant_id: tenantId,
      email: `cancel-reissue-${userId}@example.com`,
      password: 'password',
      first_name: 'Test',
      last_name: 'Admin',
      verified: true,
      createdby_id: userId,
      updatedby_id: userId,
    })
    .execute();
  await db
    .insertInto('campaigns')
    .values({
      id: campaignId,
      tenant_id: tenantId,
      admin_id: userId,
      name: 'Office',
      kind: 'office',
      createdby_id: userId,
      updatedby_id: userId,
    })
    .execute();
  await db
    .insertInto('households')
    .values({
      id: householdId,
      tenant_id: tenantId,
      campaign_id: campaignId,
      street_num: '12',
      street1: 'Maple Ave',
      city: 'Ottawa',
      state: 'ON',
      zip: 'K1A 0A1',
      country: 'Canada',
      createdby_id: userId,
      updatedby_id: userId,
    })
    .execute();
  await db
    .updateTable('tenants')
    .set({ admin_id: userId, createdby_id: userId, placeholder_household_id: householdId })
    .where('id', '=', tenantId)
    .execute();
  await db
    .insertInto('persons')
    .values({
      id: personId,
      tenant_id: tenantId,
      campaign_id: campaignId,
      household_id: householdId,
      first_name: 'Dana',
      last_name: 'Donor',
      email: 'dana@example.com',
      createdby_id: userId,
      updatedby_id: userId,
    })
    .execute();

  return { tenantId, userId, campaignId, householdId, personId };
}

async function insertDonation(
  db: any,
  seed: { tenantId: string; campaignId: string; personId: string },
  amountCents: number,
  extras: Record<string, unknown> = {},
): Promise<string> {
  const row = await db
    .insertInto('donations')
    .values({
      tenant_id: seed.tenantId,
      campaign_id: seed.campaignId,
      person_id: seed.personId,
      amount: amountCents,
      status: 'succeeded',
      method: 'cash',
      first_name: 'Dana',
      last_name: 'Donor',
      email: 'dana@example.com',
      street: '12 Maple Ave',
      city: 'Ottawa',
      state: 'ON',
      zip: 'K1A 0A1',
      country: 'Canada',
      ...extras,
    })
    .returning('id')
    .executeTakeFirstOrThrow();
  return String(row.id);
}

async function getReceiptRow(db: any, tenantId: string, receiptId: string) {
  return db
    .selectFrom('donation_receipts')
    .selectAll()
    .where('tenant_id', '=', tenantId)
    .where('id', '=', receiptId)
    .executeTakeFirstOrThrow();
}

describe('DonationReceiptsController — cancel/reissue refusals', () => {
  const controller = new DonationReceiptsController();
  const db = (BaseRepository as any)._db;
  let seed: Awaited<ReturnType<typeof createSeed>>;
  const auth = () => ({ tenant_id: seed.tenantId, user_id: seed.userId });

  beforeEach(async () => {
    seed = await createSeed(db);
    await seedReceiptSettings(db, seed.tenantId, seed.userId);
  });

  afterEach(async () => {
    await cleanTenant(db, seed.tenantId);
  });

  // ── Refusals: statements ─────────────────────────────────────────────────────

  it('refuses to cancel a statement, leaving the row untouched', async () => {
    await insertDonation(db, seed, 10000);
    const year = new Date().getFullYear();
    const statement = await controller.generateStatementForDonor(seed.tenantId, seed.personId, year, seed.userId);
    if (!statement) throw new Error('expected a statement');
    expect(statement.kind).toBe('statement');

    await expect(controller.cancelReceipt(auth(), statement.id, 'oops')).rejects.toThrow(
      /regenerated by rerunning the year, not cancelled/,
    );

    const row = await getReceiptRow(db, seed.tenantId, statement.id);
    expect(row.status).toBe('issued');
    expect(row.cancelled_at).toBeNull();
  });

  it('refuses to reissue a statement, leaving the row untouched', async () => {
    await insertDonation(db, seed, 10000);
    const year = new Date().getFullYear();
    const statement = await controller.generateStatementForDonor(seed.tenantId, seed.personId, year, seed.userId);
    if (!statement) throw new Error('expected a statement');

    await expect(controller.reissueReceipt(auth(), statement.id, 'oops')).rejects.toThrow(
      /regenerated by rerunning the year, not reissued/,
    );

    const row = await getReceiptRow(db, seed.tenantId, statement.id);
    expect(row.status).toBe('issued');
    expect(row.replaces_receipt_id).toBeNull();

    // No successor was created and no serial was consumed by the refused attempt.
    const successors = await db
      .selectFrom('donation_receipts')
      .selectAll()
      .where('tenant_id', '=', seed.tenantId)
      .where('replaces_receipt_id', '=', statement.id)
      .execute();
    expect(successors).toHaveLength(0);
  });

  // ── Refusals: acknowledgements ───────────────────────────────────────────────

  it('refuses to reissue an acknowledgement, leaving the row untouched', async () => {
    const donationId = await insertDonation(db, seed, 4200);
    const { receipt } = await controller.issueAcknowledgement(seed.tenantId, donationId, seed.userId);
    if (!receipt) throw new Error('expected an acknowledgement');

    await expect(controller.reissueReceipt(auth(), receipt.id, 'oops')).rejects.toThrow(
      /Acknowledgements are not reissued/,
    );

    const row = await getReceiptRow(db, seed.tenantId, receipt.id);
    expect(row.status).toBe('issued');
    expect(row.replaces_receipt_id).toBeNull();
  });

  // ── Refusals: double-cancel ───────────────────────────────────────────────────

  it('refuses to cancel a receipt that is already cancelled', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const receipt = await controller.issueReceipt(auth(), d1, {});
    await controller.cancelReceipt(auth(), receipt.id, 'first cancel');

    await expect(controller.cancelReceipt(auth(), receipt.id, 'second cancel')).rejects.toThrow(/already cancelled/);

    const row = await getReceiptRow(db, seed.tenantId, receipt.id);
    expect(row.cancelled_reason).toBe('first cancel'); // the second attempt did not overwrite it
  });

  // ── Refusals: reissue without a reason ───────────────────────────────────────

  it('refuses to reissue a still-issued receipt without a reason', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const receipt = await controller.issueReceipt(auth(), d1, {});

    await expect(controller.reissueReceipt(auth(), receipt.id)).rejects.toThrow(/reason/i);
    await expect(controller.reissueReceipt(auth(), receipt.id, '   ')).rejects.toThrow(/reason/i);

    const row = await getReceiptRow(db, seed.tenantId, receipt.id);
    expect(row.status).toBe('issued');
    expect(row.replaces_receipt_id).toBeNull();
  });

  // ── Refusals: workspace regime changed since issuance ────────────────────────

  it('refuses to reissue when the workspace regime no longer matches the frozen receipt', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const receipt = await controller.issueReceipt(auth(), d1, {});
    expect(receipt.regime).toBe('cra_charity');

    // Switch the workspace to a different, independently-issuable regime (political_federal only
    // additionally requires an agent name; org_legal_name is already seeded).
    await setSetting(db, seed.tenantId, seed.userId, 'receipts.regime', 'political_federal');
    await setSetting(db, seed.tenantId, seed.userId, 'receipts.agent_name', 'Financial Agent');

    await expect(controller.reissueReceipt(auth(), receipt.id, 'address correction')).rejects.toThrow(
      /regime changed since this receipt was issued/,
    );

    const row = await getReceiptRow(db, seed.tenantId, receipt.id);
    expect(row.status).toBe('issued');
    expect(row.regime).toBe('cra_charity');
    expect(row.replaces_receipt_id).toBeNull();
  });

  // ── Refusals: nothing left to reissue (every covered gift refunded) ──────────

  it('refuses to reissue a cumulative receipt whose only covered gift was refunded', async () => {
    const paymentIntentId = `pi_allref_${seed.tenantId}`;
    await insertDonation(db, seed, 8000, { stripe_payment_intent_id: paymentIntentId });
    const year = new Date().getFullYear();
    const cumulative = await controller.issueCumulativeReceipt(auth(), seed.personId, year, {});

    await new DonationsController().reverseDonation(seed.tenantId, seed.userId, {
      paymentIntentId,
      invoiceId: null,
      status: 'refunded',
    });
    const cancelledByHook = await getReceiptRow(db, seed.tenantId, cumulative.id);
    expect(cancelledByHook.status).toBe('cancelled');
    expect(cancelledByHook.reissue_required).toBe(true);

    await expect(controller.reissueReceipt(auth(), cumulative.id)).rejects.toThrow(/nothing left to reissue/);

    const row = await getReceiptRow(db, seed.tenantId, cumulative.id);
    expect(row.status).toBe('cancelled');
    expect(row.reissue_required).toBe(true); // refusal did not clear the flag or write a successor
    const successors = await db
      .selectFrom('donation_receipts')
      .selectAll()
      .where('tenant_id', '=', seed.tenantId)
      .where('replaces_receipt_id', '=', cumulative.id)
      .execute();
    expect(successors).toHaveLength(0);
  });

  // ── Refusals: donor has no mailing address at reissue time ───────────────────

  it('refuses to reissue when the donor now has no resolvable mailing address', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const receipt = await controller.issueReceipt(auth(), d1, {});

    // Strip both address sources: the donation's own snapshot and the household's.
    await db
      .updateTable('donations')
      .set({ street: null, city: null, zip: null })
      .where('tenant_id', '=', seed.tenantId)
      .where('id', '=', d1)
      .execute();
    await db
      .updateTable('households')
      .set({ street_num: null, street1: null, city: null })
      .where('id', '=', seed.householdId)
      .execute();

    await expect(controller.reissueReceipt(auth(), receipt.id, 'address correction')).rejects.toThrow(
      /no mailing address/,
    );

    const row = await getReceiptRow(db, seed.tenantId, receipt.id);
    expect(row.status).toBe('issued');
    expect(row.replaces_receipt_id).toBeNull();
  });

  // ── Refusals: frozen advantage now exceeds the surviving gifts ───────────────

  it('refuses to reissue when the recorded advantage exceeds what survives after a partial refund', async () => {
    const paymentIntentId = `pi_partial_${seed.tenantId}`;
    const d1 = await insertDonation(db, seed, 6000, { stripe_payment_intent_id: paymentIntentId });
    await insertDonation(db, seed, 6000);
    const year = new Date().getFullYear();
    // 8000 < 12000 total, so issuance's own validateAdvantage passes.
    const cumulative = await controller.issueCumulativeReceipt(auth(), seed.personId, year, { advantageCents: 8000 });
    expect(cumulative.advantage_cents).toBe(8000);

    await new DonationsController().reverseDonation(seed.tenantId, seed.userId, {
      paymentIntentId,
      invoiceId: null,
      status: 'refunded',
    });
    const cancelledByHook = await getReceiptRow(db, seed.tenantId, cumulative.id);
    expect(cancelledByHook.status).toBe('cancelled');
    expect(cancelledByHook.reissue_required).toBe(true);

    // Only d2 (6000) survives; the frozen advantage (8000) now exceeds it.
    await expect(controller.reissueReceipt(auth(), cumulative.id)).rejects.toThrow(
      /advantage now exceeds the surviving gifts/,
    );

    const row = await getReceiptRow(db, seed.tenantId, cumulative.id);
    expect(row.status).toBe('cancelled');
    expect(row.reissue_required).toBe(true);
    expect(row.advantage_cents).toBe(8000); // predecessor untouched
  });

  // ── Refusals: cross-tenant access ────────────────────────────────────────────

  it('refuses cancel/reissue on a receipt id belonging to another tenant', async () => {
    const otherSeed = await createSeed(db);
    await seedReceiptSettings(db, otherSeed.tenantId, otherSeed.userId);
    try {
      const d1 = await insertDonation(db, seed, 10000);
      const receipt = await controller.issueReceipt(auth(), d1, {});

      const otherAuth = { tenant_id: otherSeed.tenantId, user_id: otherSeed.userId };
      await expect(controller.cancelReceipt(otherAuth, receipt.id, 'not my receipt')).rejects.toThrow(/not found/i);
      await expect(controller.reissueReceipt(otherAuth, receipt.id, 'not my receipt')).rejects.toThrow(/not found/i);

      const row = await getReceiptRow(db, seed.tenantId, receipt.id);
      expect(row.status).toBe('issued');
      expect(row.replaces_receipt_id).toBeNull();

      // Nothing was written into the other tenant's receipts table either.
      const leaked = await db
        .selectFrom('donation_receipts')
        .selectAll()
        .where('tenant_id', '=', otherSeed.tenantId)
        .execute();
      expect(leaked).toHaveLength(0);
    } finally {
      await cleanTenant(db, otherSeed.tenantId);
    }
  });

  // ── Positive controls ─────────────────────────────────────────────────────────

  it('cancels an issued per-gift receipt, recording the reason', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const receipt = await controller.issueReceipt(auth(), d1, {});

    const cancelled = await controller.cancelReceipt(auth(), receipt.id, 'Wrong donor address');
    expect(cancelled.status).toBe('cancelled');
    expect(cancelled.cancelled_reason).toBe('Wrong donor address');
    expect(cancelled.cancelled_by).toBe(seed.userId);
    expect(cancelled.reissue_required).toBe(false);
  });

  it('reissues an issued receipt: successor takes the next serial, predecessor is cancelled with the reason', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const original = await controller.issueReceipt(auth(), d1, {});
    expect(original.serial).toBe(1);

    const successor = await controller.reissueReceipt(auth(), original.id, 'Donor name misspelled');
    expect(successor.serial).toBe(2);
    expect(successor.status).toBe('issued');
    expect(successor.replaces_receipt_id).toBe(original.id);

    const predecessor = await getReceiptRow(db, seed.tenantId, original.id);
    expect(predecessor.status).toBe('cancelled');
    expect(predecessor.cancelled_reason).toBe('Donor name misspelled');
  });

  it('reissues an already-cancelled reissue_required receipt without a reason and clears the flag', async () => {
    const paymentIntentId = `pi_flagged_${seed.tenantId}`;
    await insertDonation(db, seed, 10000);
    await insertDonation(db, seed, 5000, { stripe_payment_intent_id: paymentIntentId });
    const cumulative = await controller.issueCumulativeReceipt(auth(), seed.personId, new Date().getFullYear(), {});
    expect(cumulative.amount_cents).toBe(15000);

    await new DonationsController().reverseDonation(seed.tenantId, seed.userId, {
      paymentIntentId,
      invoiceId: null,
      status: 'refunded',
    });
    const flagged = await getReceiptRow(db, seed.tenantId, cumulative.id);
    expect(flagged.status).toBe('cancelled');
    expect(flagged.reissue_required).toBe(true);

    // No reason needed: the predecessor is already cancelled, not still 'issued'.
    const successor = await controller.reissueReceipt(auth(), cumulative.id);
    expect(successor.amount_cents).toBe(10000); // only the surviving gift
    expect(successor.replaces_receipt_id).toBe(cumulative.id);

    const predecessor = await getReceiptRow(db, seed.tenantId, cumulative.id);
    expect(predecessor.reissue_required).toBe(false); // cleared, not re-cancelled
    expect(predecessor.status).toBe('cancelled');
  });

  // ── Numbering invariant ───────────────────────────────────────────────────────

  it('never advances or reuses the serial counter on a refused reissue attempt', async () => {
    const d1 = await insertDonation(db, seed, 10000);
    const original = await controller.issueReceipt(auth(), d1, {});
    expect(original.serial).toBe(1);

    const counterBefore = await db
      .selectFrom('receipt_counters')
      .select('n')
      .where('tenant_id', '=', seed.tenantId)
      .where('kind', '=', 'official')
      .executeTakeFirstOrThrow();
    expect(counterBefore.n).toBe(1);

    // Two refusals that are validated before the transaction (and therefore before nextSerial runs).
    await expect(controller.reissueReceipt(auth(), original.id)).rejects.toThrow(/reason/i);
    await setSetting(db, seed.tenantId, seed.userId, 'receipts.regime', 'political_federal');
    await setSetting(db, seed.tenantId, seed.userId, 'receipts.agent_name', 'Financial Agent');
    await expect(controller.reissueReceipt(auth(), original.id, 'reason given')).rejects.toThrow(/regime changed/);
    // Restore the original regime for the successful reissue below.
    await setSetting(db, seed.tenantId, seed.userId, 'receipts.regime', 'cra_charity');

    const counterAfterRefusals = await db
      .selectFrom('receipt_counters')
      .select('n')
      .where('tenant_id', '=', seed.tenantId)
      .where('kind', '=', 'official')
      .executeTakeFirstOrThrow();
    expect(counterAfterRefusals.n).toBe(1); // untouched by both refused attempts

    const successor = await controller.reissueReceipt(auth(), original.id, 'Donor name misspelled');
    expect(successor.serial).toBe(2); // no gap, no reuse of serial 1

    const d2 = await insertDonation(db, seed, 2000);
    const fresh = await controller.issueReceipt(auth(), d2, {});
    expect(fresh.serial).toBe(3); // sequence continues cleanly after the reissue
  });
});
